name: Real Time Web Chat CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: TRUE
      MONGO_URL: mongodb://localhost:27017/test
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      COOKIE_KEY_1: ${{ secrets.COOKIE_KEY_1 }}
      COOKIE_KEY_2: ${{ secrets.COOKIE_KEY_2 }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSL certificates
        run: |
          echo "${{ secrets.SSL_KEY }}" > key.pem
          echo "${{ secrets.SSL_CERT }}" > cert.pem
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm start &
      - run: npm test